### ISSUE TITLE
Path does not exist

### ISSUE THREAD

**Issue by t7yang** [fabiospampinato/vscode-projects-plus#1]
1. install projects
1. setup "projects.refreshRoots": [ "D:\\my-project-path" ]
1. F1 run projects refresh
1. F1 project open (get list), hit enter to switch project
1. vscode pop alert window: path does not exist. the path " does not seems to exist anymore on disk

tried on vscode and vscode insider get the same result :(
os: windows 10 creator update
vscode: 1.4.2 64bit

**Comment by fabiospampinato** [comment]
Can you run `Projects: edit configuration` and paste here the path found my the extension for that particular project? Is that path actually valid?

It's either finding the wrong path or failing to open it for some reason.

**Comment by t7yang** [comment]
I got an error: unable to open ": invalid file resource (file://c:\users\myaccount\vscode.projects.json).

but the config file is actually there

I deleted the preview one, and run `edit configuration` again, get the same error.

and my home path has an default config file. weird

**Comment by fabiospampinato** [comment]
I think this is the same issue as #2. I've pushed a new update that might fix it. Can you try updating the extension?

**Comment by t7yang** [comment]
negative!
1.2.2 updated. problem still there :(

**Comment by fabiospampinato** [comment]
What is the exact value of your `projects.configPath` setting as written in the settings file? I think there's probably a problem there. I set up a new Windows machine and I cannot reproduce it any other way.

**Comment by t7yang** [comment]
either leave it empty or the path of config, the former get error when `edit config` (which expected).
but both get error ( path does not exist ) when `project: open`

**Comment by fabiospampinato** [comment]
And what is the path of your config? I mean, what is the **exact** thing you wrote in the settings? I'm asking this because if you have `c:\users\myaccount\vscode.projects.json` there then that's not a valid path, because `\u` is used for writing unicode characters, and `\v` means the "vertical tab" character. You should replace those backslashes with double backslashes, so the path will effectively become `c:\\users\\myaccount\\vscode.projects.json`.

If you leave it empty the config file will be filled with fake paths like `/path/to/project` that don't point to anything in your system, that's why you are getting the error in that case.

**Comment by fabiospampinato** [comment]
Then that's the problem, `C:\Users\myusername\vscode_projects.json` is not a valid path, because `\u` is used for writing unicode characters, and `\v` means the "vertical tab" character. You should replace those backslashes with double backslashes, so the path will effectively become `C:\\Users\\myusername\\vscode_projects.json`.

If you leave it empty the config file will be filled with fake paths like `/path/to/project` that don't point to anything in your system, that's why you are getting the error in that case.

**Comment by t7yang** [comment]
no, I did add the escape char, it didnt show because of md. I updated reply.

**Comment by fabiospampinato** [comment]
I've tried using the same logic used by the top downloaded extensions to open the file, you can find it the updated extension [here](https://www.dropbox.com/s/o30xunlw0e5hlyr/vscode-projects-plus-1.2.3.vsix?dl=0). Just do a Command palette -> Install from VSIX... and restart VSC.

If it works I'll push an update, if it doesn't I'm afraid that being unable to reproduce it I won't be able to fix it.

**Comment by t7yang** [comment]
negative! tried both vscode and insiders, even disabled all extensions to make sure no other impact.

**Comment by fabiospampinato** [comment]
Damn... Does [this]
 (https://marketplace.visualstudio.com/items/itemName=alefragnani.project-manager) extension work in your environment? Try to run its "Edit Project" command.

**Comment by fabiospampinato** [comment]
Damn... Does [this](https://marketplace.visualstudio.com/items?itemName=alefragnani.project-manager) extension work in your environment? Try to run its "Edit Project" command.

**Comment by t7yang** [comment]
project manager and git project manager both work fine on my vscode. so... you infer this problem happen on my pc only?

**Comment by evandrocoan** [comment]
The `project manager` did not worked on my pc after I used the:
```
code --user-data-dir "F:\vscode\settings" --extensions-dir "F:\vscode\extensions"
```
But after the last commit https://github.com/fabiospampinato/vscode-projects-plus/commit/15cbcdf07d3c225063ea01fef7f47307fbff2ac8 this package started working here.

**Comment by fabiospampinato** [comment]
@t7yang I'm not implying anything like that. On the contrary, if it happens to you it probably happens to other people as well. I'm just saying that at the moment I have no clue on how to fix this. 

@t7yang  Can you try if it works with the latest update if you provide a new configPath?

**Comment by t7yang** [comment]
@fabiospampinato finally, yes, it works now 👍

**Comment by fabiospampinato** [comment]
I'm happy to hear that 😄 

Did you have to change `configPath` or just updating the extension was enough?

**Comment by t7yang** [comment]
both (leave it empty or path) ok. but I think it is better to make default config in vscode default user settings folder (just like project manager), because this make sync extension able to sync the config.

**Comment by fabiospampinato** [comment]
That's interesting, I haven't thought about that 🤔 Thanks for the idea.
