### ISSUE TITLE
Keeping unsaved files upon switching projects

### ISSUE THREAD

**Issue by jemhuntr** [fabiospampinato/vscode-projects-plus#18]
Hi! First of all, thanks for this wonderfully customizable plugin.

I have no experience whatsoever with how the VS Code plugin API/system works, but would it be possible to keep unsaved files within projects without having to prompt the user to save "Untitled-n" files? Basically the switcher could perhaps automatically and silently save the "Unsaved" files in a directory somewhere, keep a list of these "Unsaved" files within the project workspace/cache/config, then load and delete these files on project switch.

This has been a feature I greatly miss with Sublime's project manager. I'm used to writing TODOs that doesn't exist as a file on disk, since I would want to tarnish my `.gitignore`'s with these TODOs.

**Comment by fabiospampinato** [comment]
Thank you! :)

Can you link me this Sublime extension you're talking about? I'm curious about what features they implemented.

Your request seems unrelated to the projects manager to me, I think you should open an issue on VSC's main repository instead.

I don't think there's a way to implement this via public APIs, altough I guess VSC itself could be patched in order to provide this functionality.

I personally commit changes to my todo files.

I think you should check out two of my other extensions, one for managing todo files ([Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-todo-plus)) and the other that combines all the todos across all your projects in a single file, it's pretty nice if you're working on many different things at the same time ([Projects+ Todo+](https://marketplace.visualstudio.com/items?itemName=fabiospampinato.vscode-projects-plus-todo-plus)).

**Comment by jemhuntr** [comment]
Hi! The Sublime package manager is built-in, no extensions necessary. It makes use of the `.sublime-project` and `.sublime-workspace` file extensions to store unsaved edits to an existing file and floating "Untitled" files.

I also believe this isn't actually possible in VS Code's current state, so I guess the main repo is where this should be asked.

Problem is that in my case, my TODOs are personal and pushing them for use by other people isn't a good idea. Adding a line to every project's `.gitignore` is tedious too.

But thanks! I guess I'll just have to wait until VS Code finally gets this feature.

**Comment by V-ed** [comment]
@jemhuntr
> Adding a line to every project's .gitignore is tedious too.

You can actually tell git to globally ignore files in each projects so you don't have to add such lines to every project (which is indeed considered bad practices) : https://gist.github.com/subfuzion/db7f57fff2fb6998a16c

**Comment by fabiospampinato** [comment]
@jemhuntr Sorry I can't believe I missed your post! Was your post meant for Todo+ instead?

> Adding a line to every project's .gitignore is tedious too.

I've actually recently published a project for doing this kind of things, [autogit](https://github.com/fabiospampinato/autogit). Using it you can do that with a single `autogit shell 'echo ".todo" >> .gitignore'`, but @V-ed's approach is probably the best here.

**Comment by jemhuntr** [comment]
No worries haha. Thanks for the alternative solutions. :)
