### ISSUE TITLE
workspaces as projects

### ISSUE THREAD

**Issue by StefanoCecere** [fabiospampinato/vscode-projects-plus#22]
i really can't do this:
i have a project that has multiple directories in its workspace, that i saves as workspace
how can i open that workspace recalling the project?

**Comment by fabiospampinato** [comment]
Right now you can do this:

1. Save everyone of those directories as a project
2. Move all those projects into a group
3. Use the `Projects: Open Group` command and select this new group
4. A new VSC window will get opened with all those directories in it

Ideally it should work like this:

1. There should be a way of opening multiple directories with a single project
    - Perhaps `project.path` could accept a path to a `*.vscode-workspace` file
    - Perhaps `project.path` could accept an array of paths
    - Perhaps a new `project.paths` configuration option could be added
2. When saving a project, it should detect if there are multiple directories in the current workspace, and ask if you want to save all of them or just the current one (or maybe just save all of them).
3. If the current workspace is saved as a `*.vscode-workspace` file, then open it directly instead. (I think this is currently impossible to implement, due to missing APIs).

**Comment by StefanoCecere** [comment]
i guess this is the way to go:

> Perhaps project.path could accept a path to a *.code-workspace file

(i have already all the workspaces saved, with dozens of directories)

**Comment by fabiospampinato** [comment]
@StefanoCecere it turns out that a path to the `*.code-workspace` file can already be used as the value for "path" 😄 

I'm keeping the issue open though, as support for this could/should be improved.

**Comment by StefanoCecere** [comment]
works perfectly! :) thanks!!

**Comment by fabiospampinato** [comment]
Now if you manually set a `.code-workspace` path for one of your project it won't get overwritten the next time you run "Projects: Refresh".
