### ISSUE TITLE
Project: Open, could be named Project: Switch?

### ISSUE THREAD

**Issue by evandrocoan** [fabiospampinato/vscode-projects-plus#3]
What do you think?

Sublime Text has this project menu:

![image](https://user-images.githubusercontent.com/5332158/28479041-24c9d68a-6e31-11e7-95a2-75db5c138c78.png)

The name `Project: Open in New Window` is awesome compared with the Sublime Text, because is more intuitive than just `Open Project` Sublime Text uses for open a project is a new window.

**Comment by fabiospampinato** [comment]
I see 3 different ideas in this issue:

### Open -> Switch

I prefer "Open", it's clearer and having "Switch in New Window" sounds weird to me. Also, we already use "Switch" for group switching.

### Project menu

I'd probably implement this, but as far as I know there's no API for adding custom items to the menu.

### Open recent

Interesting, it may generate some confusion having all these commands in the palette though:
- Open
- Open in New Window
- Open Recent
- Open Recent in New Window

I'm not going to implement this right away, but if there's high enough demand I'll be happy to change my mind. In the meantime I encourage you to use groups, they provide a more powerful and predictable way of shortening the projects list.

I'm going to close this issue, but feel free to open others for `Project menu` and `Open recent`, I'll leave them open until they get implemented, so that we can monitor user demand via reactions.

**Comment by evandrocoan** [comment]
I think the names `Open Recent` and `Open Recent in New Window` should be `Project: List Recent (Switch)` and `Project: List Recent (New Window)`.

The other project manager has these entries:

> * **Project Manager: List Projects to Open** List all saved projects and pick one
> * **Project Manager: List Projects to Open in New Window** List all saved projects and pick one to be opened in New Window

1. https://github.com/alefragnani/vscode-project-manager#available-commands

**Comment by fabiospampinato** [comment]
In your example "Open" and "List" basically do the same thing, they display a list of projects to open, why should we use 2 different verbs for the same thing?

vscode-project-manage has a slighly more verbose naming convention:
- `Project Manager: List Projects to Open` maps to our `Project: Open`
- `Project Manager: List Projects to Open in New Window` maps to ur `Project: Open in New Window`

**Comment by evandrocoan** [comment]
You are right, sorry I missed that.
