### ISSUE TITLE
Enable fuzzy search to filter projects

### ISSUE THREAD

**Issue by LeBenLeBen** [fabiospampinato/vscode-projects-plus#31]
I usually have multiple projects starting with the same prefix, like the client name, and then the project. But since those are Git repositories, they are named with kebab-case; for exemple: `client-project`.

At the moment if I search for `client pro`, the project doesn't show up because of the dash between the two words.

It would be amazing if the filter could not consider non-alphanumeric characters to make it even more powerful.

Thanks for considering and for the time you put into this very nice plugin.

**Comment by fabiospampinato** [comment]
This is kind of a known issue: fuzzy search isn't really enabled everywhere 😕 https://github.com/Microsoft/vscode/issues/34088

IMHO this isn't something that should be implemented in each individual extension but in the editor itself. 

In your specific case you should write `clientpro` rather than `client pro` I think. 

> Thanks for considering and for the time you put into this very nice plugin.

Thank you :)
